version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  envoy:
    image: envoyproxy/envoy:dev-b4174e7894d62d11e8a6b304c87e319ad6400a9c
    ports:
      - "9901:9901"
      - "10000:10000" 
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
  
